/**
* Monopoly game board configuration containing all board spaces.
* 
* @type {Array<Object>}
* @property {number} id - Unique identifier for the board space (0-19)
* @property {string} name - Display name of the board space
* @property {string} type - Type of space: "start", "property", "chance", "tax", or "jail"
* @property {number} [price] - Purchase price for properties (optional)
* @property {number} [rent] - Base rent amount for properties (optional)
* @property {number} [amount] - Tax amount for tax spaces (optional)
* 
* @example
* // Access a specific board space
* const startLocation = board[0];
* 
* @example
* // Find a property by name
* const location = board.find(location => location.name === "Baltic Avenue");
*/
const board = [
  {
    id: 0,
    name: "Start",
    type: "start",
  },
  {
    id: 1,
    name: "Mediterranean Avenue",
    type: "property",
    color: "dark-purple",
    price: 60,
    houseCost: 50,
    rent: 2,
    rent1House: 10,
    rent2Houses: 30,
    rent3Houses: 90,
    rent4Houses: 160,
    rentHotel: 250,
  },
  {
    id: 2,
    name: "Chance",
    type: "chance",
  },
  {
    id: 3,
    name: "Baltic Avenue",
    type: "property",
    color: "dark-purple",
    price: 60,
    houseCost: 50,
    rent: 4,
    rent1House: 20,
    rent2Houses: 60,
    rent3Houses: 180,
    rent4Houses: 320,
    rentHotel: 450,
  },
  {
    id: 4,
    name: "Income Tax",
    type: "tax",
    amount: 200,
  },
  {
    id: 5,
    name: "Reading Railroad",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 6,
    name: "Oriental Avenue",
    type: "property",
    color: "light-blue",
    price: 100,
    houseCost: 50,
    rent: 6,
    rent1House: 30,
    rent2Houses: 90,
    rent3Houses: 270,
    rent4Houses: 400,
    rentHotel: 550,
  },
  {
    id: 7,
    name: "Chance",
    type: "chance",
  },
  {
    id: 8,
    name: "Vermont Avenue",
    type: "property",
    color: "light-blue",
    price: 100,
    houseCost: 50,
    rent: 6,
    rent1House: 30,
    rent2Houses: 90,
    rent3Houses: 270,
    rent4Houses: 400,
    rentHotel: 550,
  },
  {
    id: 9,
    name: "Connecticut Avenue",
    type: "property",
    color: "light-blue",
    price: 120,
    houseCost: 50,
    rent: 8,
    rent1House: 40,
    rent2Houses: 100,
    rent3Houses: 300,
    rent4Houses: 450,
    rentHotel: 600,
  },
  {
    id: 10,
    name: "Jail",
    type: "jail",
  },
  {
    id: 11,
    name: "St. Charles Place",
    type: "property",
    color: "purple",
    price: 140,
    houseCost: 100,
    rent: 10,
    rent1House: 50,
    rent2Houses: 150,
    rent3Houses: 450,
    rent4Houses: 625,
    rentHotel: 750,
  },
  {
    id: 12,
    name: "Electric Company",
    type: "utility",
    price: 150,
  },
  {
    id: 13,
    name: "States Avenue",
    type: "property",
    color: "purple",
    price: 140,
    houseCost: 100,
    rent: 10,
    rent1House: 50,
    rent2Houses: 150,
    rent3Houses: 450,
    rent4Houses: 625,
    rentHotel: 750,
  },
  {
    id: 14,
    name: "Virginia Avenue",
    type: "property",
    color: "purple",
    price: 160,
    houseCost: 100,
    rent: 12,
    rent1House: 60,
    rent2Houses: 180,
    rent3Houses: 500,
    rent4Houses: 700,
    rentHotel: 900,
  },
  {
    id: 15,
    name: "Pennsylvania Railroad",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 16,
    name: "St. James Place",
    type: "property",
    color: "orange",
    price: 180,
    houseCost: 100,
    rent: 14,
    rent1House: 70,
    rent2Houses: 200,
    rent3Houses: 550,
    rent4Houses: 750,
    rentHotel: 950,
  },
  {
    id: 17,
    name: "Community Chest",
    type: "community-chest",
  },
  {
    id: 18,
    name: "Tennessee Avenue",
    type: "property",
    color: "orange",
    price: 180,
    houseCost: 100,
    rent: 14,
    rent1House: 70,
    rent2Houses: 200,
    rent3Houses: 550,
    rent4Houses: 750,
    rentHotel: 950,
  },
  {
    id: 19,
    name: "New York Avenue",
    type: "property",
    color: "orange",
    price: 200,
    houseCost: 100,
    rent: 16,
    rent1House: 80,
    rent2Houses: 220,
    rent3Houses: 600,
    rent4Houses: 800,
    rentHotel: 1000,
  },
  {
    id: 20,
    name: "Free Parking",
    type: "free-parking",
  },
  {
    id: 21,
    name: "Kentucky Avenue",
    type: "property",
    color: "red",
    price: 220,
    houseCost: 150,
    rent: 18,
    rent1House: 90,
    rent2Houses: 250,
    rent3Houses: 700,
    rent4Houses: 875,
    rentHotel: 1050,
  },
  {
    id: 22,
    name: "Chance",
    type: "chance",
  },
  {
    id: 23,
    name: "Indiana Avenue",
    type: "property",
    color: "red",
    price: 220,
    houseCost: 150,
    rent: 18,
    rent1House: 90,
    rent2Houses: 250,
    rent3Houses: 700,
    rent4Houses: 875,
    rentHotel: 1050,
  },
  {
    id: 24,
    name: "Illinois Avenue",
    type: "property",
    color: "red",
    price: 240,
    houseCost: 150,
    rent: 20,
    rent1House: 100,
    rent2Houses: 300,
    rent3Houses: 750,
    rent4Houses: 925,
    rentHotel: 1100,
  },
  {
    id: 25,
    name: "B & O Railroad",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 26,
    name: "Atlantic Avenue",
    type: "property",
    color: "yellow",
    price: 260,
    houseCost: 150,
    rent: 22,
    rent1House: 110,
    rent2Houses: 330,
    rent3Houses: 800,
    rent4Houses: 975,
    rentHotel: 1150,
  },
  {
    id: 27,
    name: "Ventnor Avenue",
    type: "property",
    color: "yellow",
    price: 260,
    houseCost: 150,
    rent: 22,
    rent1House: 110,
    rent2Houses: 330,
    rent3Houses: 800,
    rent4Houses: 975,
    rentHotel: 1150,
  },
  {
    id: 28,
    name: "Waterworks",
    type: "utility",
    price: 150,
  },
  {
    id: 29,
    name: "Marvin Gardens",
    type: "property",
    color: "yellow",
    price: 280,
    houseCost: 150,
    rent: 24,
    rent1House: 120,
    rent2Houses: 360,
    rent3Houses: 850,
    rent4Houses: 1025,
    rentHotel: 1200,
  },
  {
    id: 30,
    name: "Go To Jail",
    type: "go-to-jail",
  },
  {
    id: 31,
    name: "Pacific Avenue",
    type: "property",
    color: "green",
    price: 300,
    houseCost: 200,
    rent: 26,
    rent1House: 130,
    rent2Houses: 390,
    rent3Houses: 900,
    rent4Houses: 1100,
    rentHotel: 1275,
  },
  {
    id: 32,
    name: "North Carolina Avenue",
    type: "property",
    color: "green",
    price: 300,
    houseCost: 200,
    rent: 26,
    rent1House: 130,
    rent2Houses: 390,
    rent3Houses: 900,
    rent4Houses: 1100,
    rentHotel: 1275,
  },
  {
    id: 33,
    name: "Community Chest",
    type: "community-chest",
  },
  {
    id: 34,
    name: "Pennsylvania Avenue",
    type: "property",
    color: "green",
    price: 320,
    houseCost: 200,
    rent: 28,
    rent1House: 150,
    rent2Houses: 450,
    rent3Houses: 1000,
    rent4Houses: 1200,
    rentHotel: 1400,
  },
  {
    id: 35,
    name: "Short Line",
    type: "railroad",
    price: 200,
    rent: 25,
  },
  {
    id: 36,
    name: "Chance",
    type: "chance",
  },
  {
    id: 37,
    name: "Park Place",
    type: "property",
    color: "dark-blue",
    price: 350,
    houseCost: 200,
    rent: 35,
    rent1House: 175,
    rent2Houses: 500,
    rent3Houses: 1100,
    rent4Houses: 1300,
    rentHotel: 1500,
  },
  {
    id: 38,
    name: "Luxury Tax",
    type: "tax",
    amount: 100,
  },
  {
    id: 39,
    name: "Boardwalk",
    type: "property",
    color: "dark-blue",
    price: 400,
    houseCost: 200,
    rent: 50,
    rent1House: 200,
    rent2Houses: 600,
    rent3Houses: 1400,
    rent4Houses: 1700,
    rentHotel: 2000,
  },
];

export function createBoard() {
  return board.map(createLocation);
}

function createLocation(locationDef) {
  if (locationDef.price) {
    const location = {
      ...locationDef,
      ownerId: null,
    };

    if (locationDef.type === "property") {
      return {
        ...location,
        houses: 0,
        hasHotel: false,
        isMortgaged: false,
      };
    }

    return location;
  }

  return { ...locationDef };
}
